### ISSUE TITLE
gcloud preview: "http: Hijack is incompatible with use of CloseNotifier"

### ISSUE THREAD

**Issue by Bekt** [GoogleCloudPlatform/appengine-python-vm-hello#7]
Trying to run a Google App Engine app in a vm with the Python standard runtime. ([link](https://cloud.google.com/appengine/docs/managed-vms/tutorial/step2))

Everything is up-to-date, but `gcloud` cannot preview the app with the following error:
```bash
gcloud preview app run app.yaml

INFO     2015-05-28 21:37:51,456 devappserver2.py:745] Skipping SDK update check.
INFO     2015-05-28 21:37:51,541 api_server.py:190] Starting API server at: http://localhost:50191
INFO     2015-05-28 21:37:51,589 dispatcher.py:192] Starting module "default" running at: http://localhost:8080
INFO     2015-05-28 21:37:51,590 containers.py:259] Building docker image kanat-dev.default.20150528t213751 from .../hello-sample-appengine-vm-python/Dockerfile:
INFO     2015-05-28 21:37:51,590 containers.py:261] --------------------  DOCKER BUILD  --------------------
INFO     2015-05-28 21:37:51,593 admin_server.py:118] Starting admin server at: http://localhost:8000
INFO     2015-05-28 21:37:51,674 containers.py:280] Step 0 : FROM gcr.io/google_appengine/python-compat
INFO     2015-05-28 21:37:51,714 containers.py:280] ---> b3119c5e2d23
INFO     2015-05-28 21:37:51,715 containers.py:280] Step 1 : ADD . /app
INFO     2015-05-28 21:37:52,040 containers.py:280] ---> f3fda8e97e08
INFO     2015-05-28 21:37:52,047 containers.py:280] Removing intermediate container c31b3136e3ed
INFO     2015-05-28 21:37:52,047 containers.py:280] Successfully built f3fda8e97e08
INFO     2015-05-28 21:37:52,052 containers.py:292] --------------------------------------------------------
INFO     2015-05-28 21:37:52,053 containers.py:304] Image kanat-dev.default.20150528t213751 built, id = f3fda8e97e08
INFO     2015-05-28 21:37:52,053 containers.py:534] Creating container...
INFO     2015-05-28 21:37:52,151 containers.py:560] Container 8c4d875c46c2b2eb9ea7beda58b708f890bff05052d32c07730b904af4d095ac created.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File ".../google-cloud-sdk/platform/google_appengine/google/appengine/tools/docker/containers.py", line 643, in _ListenToLogs
    for line in log_lines:
  File ".../google-cloud-sdk/./lib/docker/docker/client.py", line 229, in _multiplexed_response_stream_helper
    socket = self._get_raw_response_socket(response)
  File ".../google-cloud-sdk/./lib/docker/docker/client.py", line 171, in _get_raw_response_socket
    self._raise_for_status(response)
  File ".../google-cloud-sdk/./lib/docker/docker/client.py", line 122, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("http: Hijack is incompatible with use of CloseNotifier")

INFO     2015-05-28 21:37:53,464 module.py:1745] New instance for module "default" serving on:
http://localhost:8080

INFO     2015-05-28 21:37:53,579 module.py:788] default: "GET /_ah/start HTTP/1.1" 404 52
```

```bash
$ docker images
REPOSITORY                              TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
...
gcr.io/google_appengine/python-compat   latest              b3119c5e2d23        5 weeks ago         281.1 MB

$ boot2docker version
Boot2Docker-cli version: v1.6.2
Git commit: cb2c3bc

$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

$ gcloud version
Google Cloud SDK 0.9.61

app 2015.05.19
app-engine-go-darwin-x86_64 1.9.20
app-engine-java 1.9.20
app-engine-python 1.9.20
bq 2.0.18
bq-nix 2.0.18
compute 2015.05.19
core 2015.05.19
core-nix 2014.10.20
dns 2015.05.19
gcloud 2015.05.19
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.12
gsutil-nix 4.6
kubectl 
kubectl-darwin-x86_64 0.17.0
preview 2015.05.19
sql 2015.05.06
```

**Comment by Bekt** [comment]
It runs fine if I take out VM related options from `app.yaml`.

```
vm: true

manual_scaling:
  instances: 1
```

**Comment by fotinakis** [comment]
This seems to be fixed in the latest version of the google-cloud-sdk (you may also have to update your docker version, if you're on mac just run `boot2docker upgrade`)

**Comment by Bekt** [comment]
We've switched to AWS :/
